name: Bug Report
description: Report a bug in DIL validator, CLI, or specification
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please fill out the sections below.

  - type: input
    id: version
    attributes:
      label: DIL Version
      description: "Output of `dil --version`"
      placeholder: "0.1.0"
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      options:
        - Validator
        - CLI
        - Installer
        - Specification
        - Documentation
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to reproduce the issue
      placeholder: |
        1. Create a file `test.dil` with content...
        2. Run `dil validate test.dil`
        3. Observe...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: OS, Node.js version, relevant logs, etc.
    validations:
      required: false
